### PR TITLE
feat: Enabling default list of endpoints via config

### PR DESCRIPTION
**Pull request by codegrunt**
Enabling the use of the config.json to allow for a default list of endpoints to be populated on first load of the Fluidd interface.

Signed-off-by: Chris Owen <Chris@ChrisOwen.org>

### CODE REVIEW

**Comment by codegrunt** [comment]
I found this work-item and was looking at enabling this for myself:
https://github.com/fluidd-core/fluidd/issues/464

this primarily was for docker, and the next planned steps would be to create a "refresh: in the settings.  If this doesnt fit your vision just give me a direction and I will see if I can make those changes for you.

**Comment by pedrolamas** [comment]
I like the idea here, but I'm not sure of the necessity of the `sanitizeEndpoint` method - this is an advanced feature, if users are going to use it, they better know what they are doing and set correct URLs!

**Comment by codegrunt** [comment]
not saying it's necessary, and if you do not want it, easy enough to remove.  Mostly built it so that it wouldn't throw errors and stop the initialization of the webpage since it is happening in the bootstrapping of the SPA.

**Comment by pedrolamas** [comment]
> Mostly built it so that it wouldn't throw errors and stop the initialization of the webpage since it is happening in the bootstrapping of the SPA.

That's a very good point and makes complete sense!

**Review by pedrolamas — APPROVED** [review]

**Review by matmen — APPROVED** [review]
LGTM

**Pull request merged**
