### PR TITLE
fix: display correct fan speed when using 'fan max_power' setting

### LINKED ISSUE #390: Fan speed UI does not adjust for [fan] max_power
## Affected Version(s):
- klipper version: v1.16.2
- moonraker version: v0.9.1-670-gfa7a91a3
- fluidd version: v0.7.1-35-g5204fe3

## Platform:
RaspberryPi 4 + Chrome

## Reproduction Steps:
- Configured my fan to run at maximum half power,
```
[fan]
max_power: 0.5
```

- Use UI to adjust fan speed to 100% (this issues M106 S255 as expected)
- UI now displays 50% instead (expected to see 100%)

## Actual Results:
UI reports half of the expected fan speed value

## Expected Results:
UI should report fan speed adjusted for max_power

## Additional information
It's actually Moonraker reporting `"fan": {"speed": 0.5}` after we sent `M106 S255`.
I considered filing this as a Moonraker issue, but when checking Mainsail, it seems they adjust for `max_power` on their end.

### PR DESCRIPTION
**Pull request by Vhab**
Fixes the Fan slider misbehaving when the 'max_power' setting is used. (Fixes #390)

As the slider goes from 0 to 1, I did have the option to adjust the maximum value of the slider to max_power. This is what Mainsail has done.

However, it felt less intrusive to adjust the value received from Moonraker rescaled to 0-1 using max_power instead.

### CODE REVIEW

**Comment by Vhab** [comment]
Follow up on the concern whether Fluidd is the right place to fix this.

Klipper's developer expressed he does not intend to change Klipper's behavior, but would prefer to clarify the documentation (https://github.com/KevinOConnor/klipper/pull/4622#issuecomment-909730638).

Thus fixing this at the Fluidd level seems appropriate.

**Review by ForsakenHarmony — APPROVED** [review]

**Review by dweight — APPROVED** [review]

**Comment by Vhab** [comment]
Would it be possible to merge this?

**Review by Biorn1950 — APPROVED** [review]

**Comment by Biorn1950** [comment]
@pedrolamas this PR is ok.
idk if you prefer to keep the current format which would give that:
`return (this.fan.speed) ? Math.round(this.fan.speed / (this.fan.config.max_power || 1) * 100) : 0`

**Comment by pedrolamas** [comment]
I'm perfectly fine with this one!

**Review by pedrolamas — APPROVED** [review]

**Review by eduncan911 — APPROVED** [review]
LGTM, though idk what `max_power` holds.

**Comment by Biorn1950** [comment]
> LGTM, though idk what `max_power` holds.

it's the max pwm value.

**Pull request merged**
