### PR TITLE
Fix: directory sorting

### PR DESCRIPTION
**Pull request by trapeznikov-ap**
The top directory ".." should always be the first in the list when sorting

### CODE REVIEW

**Comment by pedrolamas** [comment]
Hi @trapeznikov-ap, thank you for your PR.

From what I can see on my own machine, the ".." always appears on top, no matter what file list I'm looking at, so I was just wondering where did you see this behavior broken?

**Comment by trapeznikov-ap** [comment]
> Hi @trapeznikov-ap, thank you for your PR.
> 
> From what I can see on my own machine, the ".." always appears on top, no matter what file list I'm looking at, so I was just wondering where did you see this behavior broken?

At me the problem is shown at sorting in descending order by names. Tell me the sort direction and which column are you sorting by?

**Comment by pedrolamas** [comment]
Can you send a screenshot showing this behavior? Are you using cyrillic chars for your filenames and folders?

From me, using regular chars it is working as normal when ordering by Name ascending and descending, so ".." is always on top.

**Comment by trapeznikov-ap** [comment]
image
image
image

**Review by pedrolamas — APPROVED** [review]

**Review by Biorn1950 — APPROVED** [review]

**Pull request merged**
