### PR TITLE
docs(obico): remote access page refresh

### PR DESCRIPTION
**Pull request by kennethjiang**
We have added a lot of stuff since the last update, including the full remote access to fluidd page.

### CODE REVIEW

**Review by pedrolamas — APPROVED** [review]

**Comment by kennethjiang** [comment]
Thank you @pedrolamas !

**Comment by pedrolamas** [comment]
Thank you @kennethjiang , can you please add a footer to the main PR comment with a "Signed-off-by" line, following the [CONTRIBUTING](https://github.com/fluidd-core/fluidd/blob/develop/CONTRIBUTING.md) guidelines.

**Comment by kennethjiang** [comment]
> Thank you @kennethjiang , can you please add a footer to the main PR comment with a "Signed-off-by" line, following the [CONTRIBUTING](https://github.com/fluidd-core/fluidd/blob/develop/CONTRIBUTING.md) guidelines.

Sorry for not following the guideline! Just amended the commit.

**Review by pedrolamas — APPROVED** [review]

**Review by pedrolamas — CHANGES_REQUESTED** [review]
Apologies @kennethjiang but we are having trouble merging this PR as the changes need to be done on the "develop" branch and not on the "master" branch.

It will probably be easier for you to close this PR, change to "develop" branch, make the changes there, push to a new PR, and then we can merge it down.

**Comment by kennethjiang** [comment]
Sorry for the delay. Opened https://github.com/fluidd-core/fluidd/pull/1187. Let me know if that PR works @pedrolamas

**Pull request closed without merging**
