### PR TITLE
Feat: Apply_Z_Offset

### LINKED ISSUE #57: Probe calibration ++ in printer menu

### LINKED ISSUE #65: FR: Add Save baby step to printer.cfg for easy z end stop calibration Prusa style
after doing a z endstop calibrate we have a rought position of the z that need to be adjusted with baby stepping. I then edit the endstop position in printer.cfg. Does it sound possible to implement the following in fluidd : allow a save of baby stepping that effectively affect z endstop position in printer.cfg 

Already discuss here : 
https://discord.com/channels/460117602945990666/776483964587474974/780405538831335464

But I would like to add it here to avoid forgetting this one

### PR DESCRIPTION
**Pull request by Biorn1950**
Resolves #57, Resolves #65

Signed-off-by: Biorn1950 <biorn@me.com>

### CODE REVIEW

**Comment by Biorn1950** [comment]
https://github.com/fluidd-core/fluidd/issues/57

**Comment by Biorn1950** [comment]
Resolves #57

**Comment by Biorn1950** [comment]
close #57

**Comment by Biorn1950** [comment]
Resolves #65

**Review by pedrolamas — APPROVED** [review]
LGTM

**Pull request merged**
