### PR TITLE
feat: display gcode progress in overlay rather than dialog

### PR DESCRIPTION
**Pull request by kieraneglin**
re-attempt at #1029

Loading a file into the gcode viewer opens a dialog that removes control until the file is parsed. This has some potentially nasty effects like delaying access to the emergency stop button, but it's also a minor and recurring annoyance. Based on that, I've moved the parsing progress information into the gcode card itself, lessening the time that control is removed from the user.

Eventually I'd like to provide a mechanism to optionally display file download progress as an overlay (or some other mechanism that retains user control), but that's not captured in this PR.

Signed-off-by: Kieran Eglin <kieran.eglin@gmail.com>

Screen Shot 2023-02-13 at 3 23 27 PM
Screen Shot 2023-02-13 at 3 23 52 PM

### CODE REVIEW

**Comment by kieraneglin** [comment]
@pedrolamas do you think there's interest in this PR?

**Comment by pedrolamas** [comment]
I do see value in this PR, only I'm not entirely convinced of the approach.... I need to think a bit longer on it!

Having said that, we may be looking at this from the wrong side: the real problem is that the Emergency Stop button should ALWAYS be accessible, which is not the case when these dialogs are open!

**Comment by kieraneglin** [comment]
@pedrolamas thank you for the feedback! The emergency stop issue is definitely pressing, but for me the main aspect of it is the annoyance of opening my web interface for a quick change or status update and having the download + parsing dialog holds that up. I'll be the first to admit that it's a minor thing, but it's a fairly frequent annoyance. 

Approach aside, my ideal goal would be having the file download progress/controls and the parsing progress contained entirely within the g-code viewer card so that it's not interfering with the use of the rest of the dashboard. 

Again, just let me know if that's not something you're interested in adding!

**Comment by pedrolamas** [comment]
Implemented in e28a958f77198b94947720bae3135a42b4e46180

**Pull request closed without merging**
