### PR TITLE
feat: add finish time selection from slicer or file

### LINKED ISSUE #1373: Finish Time (ETA) Selection, Slicer / File
### Is your feature request related to a problem? Please describe

Sometimes the "File" ETA is not precise. 

### Describe the solution you'd like

Currently, the Finish Time is estimated from the "File" time. Sometimes, this is somewhat off the real printing duration, where "Slicer" estimated time is more precise. It would be great if we could have the option to choose between File and Slicer for ETA. 

### Describe alternatives you've considered

A simple radio button or pull-down selection menu on Settings would be sufficient. 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MadeBaruna**
added options on general setting with file or slicer for finish time and progress 
close #1373 

file:

slicer:

### CODE REVIEW

**Comment by pedrolamas** [comment]
Hi @MadeBaruna, thank you for your work on this Pull Request, this was an absolute stellar job! 🙂

I made a couple of changes to it, but the most important is that I added the possibility to select more than one data source for the Print Progress and Print ETA (so when more than one is selected, we will display an average)

**Comment by pedrolamas** [comment]
Here's how it currently looks on the settings side:

image

**Review by pedrolamas — APPROVED** [review]

**Review by matmen — APPROVED** [review]
Nice work, LGTM! Thanks

**Comment by yw4z** [comment]
@pedrolamas what about adding an average of both as option

**Comment by pedrolamas** [comment]
> what about adding an average of both as option

@yw4z just tick both checkboxes and it will calculate an average! 🙂

**Comment by yw4z** [comment]
@pedrolamas nice to see you already added but using a radio button with separate options would be better to show there is an average option. also i will share a detailed design mockup soon for print status section :) which section is best to share at discussion / issues

**Comment by pedrolamas** [comment]
@yw4z it literally says so on the description, not sure what else we could do here to improve it... 🤔

image

**Comment by yw4z** [comment]
@pedrolamas people like me don't read much i guess :)

**Pull request merged**
