### PR TITLE
feat: graduates g-code previewer to non-beta

### LINKED ISSUE #181: GCODE preview
A gcode preview like octoprint has would be very usefull, especially if it can sync up to the current print

### PR DESCRIPTION
**Pull request by pedrolamas**
Closes #181

Signed-off-by: Pedro Lamas <pedrolamas@gmail.com>

### CODE REVIEW

**Review by matmen — APPROVED** [review]

**Comment by AntoszHUN** [comment]
Hi! I've updated the Hungarian language several times, but I don't see the change in Fluidd's web interface. Why is this?

Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

**Comment by pedrolamas** [comment]
> Hi! I've updated the Hungarian language several times, but I don't see the change in Fluidd's web interface. Why is this?

Hi @AntoszHUN, that's because your changes are only on the develop branch and will only be available on the master branch when we release a new version.

There was a mistake today where some code got inadvertently merged to master branch, that was reverted as we are not ready to release it yet.

Can I ask that you post either on your PRs, by opening a new issue, or just come to us on Discord? Using non-related PRs is not ideal... thank you!

**Comment by AntoszHUN** [comment]
> > Hi! I've updated the Hungarian language several times, but I don't see the change in Fluidd's web interface. Why is this?
> 
> Hi @AntoszHUN, that's because your changes are only on the develop branch and will only be available on the master branch when we release a new version.
> 
> There was a mistake today where some code got inadvertently merged to master branch, that was reverted as we are not ready to release it yet.
> 
> Can I ask that you post either on your PRs, by opening a new issue, or just come to us on Discord? Using non-related PRs is not ideal... thank you!

I mean so update to the next version. It's so clear. I thought the OS was just updated. But then it has nothing to do with Fluidd. How do I know if an update or a new version is coming? I have Klipper, Moonraker, KlipperScreen, and OS on my web interface. There is no fluid. How is it updated? Do I need to reinstall?

**Comment by matmen** [comment]
> There is no fluid. How is it updated? Do I need to reinstall?

add
```yml
[update_manager client fluidd]
type: web
repo: fluidd-core/fluidd
path: ~/fluidd
```
to your `moonraker.conf`

And as Pedro already stated, please use our Discord server for support requests, not random PRs. Hope this helps.

**Comment by AntoszHUN** [comment]
> 

Thanks! Sorry. I don't have a Discord. I do not speak English. So there are several reasons I don’t use it. Why an extra program if it's easier to write here?

**Pull request merged**
