### PR TITLE
feat: Adds toolhead circle style controls

### PR DESCRIPTION
**Pull request by vajonam**
adds the cricle control for the toolhead.

https://github.com/fluidd-core/fluidd/assets/152501/2eb591b2-bfc3-4595-bc41-6050f04ba864

- includes un-homed states (warning color)
- homed and z_tilt adjusted (need someone to verify QGL is working) 
- added settings for circle control, including 4 element array for steps
- added setting for XY homing

### CODE REVIEW

**Comment by vajonam** [comment]
I will add the loading indicators features a new PR, that is bit more involved. please review and suggest and code changes, am sure there will be a few.

**Comment by vajonam** [comment]
@pedrolamas  I don't think I have considered force move, to enable the step buttons.

**Comment by pedrolamas** [comment]
@vajonam you might want to hold off on doing changes for now as I am looking at full theming of this!

**Comment by vajonam** [comment]
Yup am not pushing on this branch, its all yours.

**Comment by pedrolamas** [comment]
## Dark theme

image

## Light theme

image

**Review by pedrolamas — DISMISSED** [review]

**Review by pedrolamas — APPROVED** [review]

**Review by matmen — APPROVED** [review]
Great work, love it!
@pedrolamas Feel free to merge if you're ready

**Pull request merged**
