### PR TITLE
Gcode viewer fixes

### PR DESCRIPTION
**Pull request by Mechazawa**
This PR adds the ability to group lower layers and fixes the follow progress feature. The "group lower layers" is usefull for when you have a wipe or something at your gcode start. The follow progress feature didn't work because the parser didn't increase the filesize counter when parsing comment lines. This has been fixed and I've confirmed that it's now following the progress correctly. 

Signed-off-by: Bas <mega@ioexception.at>

### CODE REVIEW

**Review by pedrolamas — CHANGES_REQUESTED** [review]
From my tests, this is working fine, but I would ask that you make the code changes indicated (rename `groupLower` to `groupLowerLayers` and `group_lower` and `group_lower_layers`).

Please also revert the changes to package-lock.json file, we will do that separately in a different commit.

**Review by pedrolamas — APPROVED** [review]
I made a minor change to the PR to ensure this feature is disabled by default (so it will be an opt-in feature)

Nevertheless, it's all fine and LGTM!

**Comment by pedrolamas** [comment]
@Mechazawa I was just about to merge this in when I noticed that you didn't follow the [CONTRIBUTING.md](https://github.com/fluidd-core/fluidd/blob/develop/CONTRIBUTING.md) rules, specifically the part about following the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard.

Can you please edit the original comment on the PR to at least have `Signed-off-by: Your Name <your email address>` as the last line?

**Comment by Mechazawa** [comment]
Signed off 👍

**Comment by pedrolamas** [comment]
@Mechazawa sorry to ping you on this "old" issue, but I've been doing some tests around the gcode previewer, and I noticed that the "group lower layers" fails when I use it with multi-object prints.

But the main reason I'm now pinging you is that I still don't understand the use case for the "group lower layers"... can you explain or provide some sort of example gcode I can try under the simulavr docker container?

Thank you!

**Pull request merged**
