### PR TITLE
fix: FileSystemBrowser icon size and resolution

### PR DESCRIPTION
**Pull request by pedrolamas**
Before the changes on 0a3f8de1a0e71c01cc2bf54a6ad3985d88369c32, the FileSystemBrowser icon size was 16px, but this was changed to a minimum (default) of 32px.

This caused an UI change, but more importantly, the icons on retina style displays now show with dithering (as the system is scaling a 32px raster image to 64px)

Before the changes on 0a3f8de1a0e71c01cc2bf54a6ad3985d88369c32:

image

After the changes on 0a3f8de1a0e71c01cc2bf54a6ad3985d88369c32 (shows dithering as the 32px raster image is rendered at 200%):

image

After the changes on this PR (32px raster image shown as 200% 16px icon):

image

Also part of the changes on this PR, the 32px icon rendered with no dithering as it is using the large thumbnail:

image

Signed-off-by: Pedro Lamas <pedrolamas@gmail.com>

### CODE REVIEW

**Comment by matmen** [comment]
Was this really 16px before? I feel like 32px seems right, and https://github.com/fluidd-core/fluidd/commit/0a3f8de1a0e71c01cc2bf54a6ad3985d88369c32#diff-6fcb9b7e86a444e00e2251ed6079f930ecc08845787711088fca27559a1afc8aL452 shows the height to be 32px (in width too assuming square thumbnails)

**Comment by pedrolamas** [comment]
By having the class "dense", we were then forcing the icon to be show at 16px:

https://github.com/fluidd-core/fluidd/blob/0a3f8de1a0e71c01cc2bf54a6ad3985d88369c32/src/components/widgets/filesystem/FileSystemBrowser.vue#L72

https://github.com/fluidd-core/fluidd/blob/0a3f8de1a0e71c01cc2bf54a6ad3985d88369c32/src/components/widgets/filesystem/FileSystemBrowser.vue#L448-L450

**Comment by pedrolamas** [comment]
I think this is now in a proper working way!

**Review by matmen — APPROVED** [review]
LGTM

**Pull request merged**
