### PR TITLE
feat(spoolman): handle v2 responses, improve connection error handling

### PR DESCRIPTION
**Pull request by matmen**
Adds support for the v2 responses and events proposed in https://github.com/Arksine/moonraker/pull/792

Emits errors via toast notifications (on initial load) and shows a disconnected/out-of-sync state more clearly:
image

### CODE REVIEW

**Review by pedrolamas — APPROVED** [review]

**Comment by thijstriemstra** [comment]
Shouldn't "it" be a 1.28 version, 1.27.2 sounds like a minor minor update to 1.27.1 @pedrolamas

**Comment by pedrolamas** [comment]
> Shouldn't "it" be a 1.28 version? 1.27.2 sounds like a minor minor update to 1.27.1 @pedrolamas

Indeed!!

When we release an updated version, we normally create a new patch Milestone just after it so we can start assigning stuff for the next release, and when we see it is getting bigger than a patch release, we just change it to the next minor version - which is what I am about to do now! 🙂

**Comment by thijstriemstra** [comment]
thanks for the update. It's been quite a while since last release, any ETA for the next @pedrolamas?

**Comment by pedrolamas** [comment]
KungFuPandaLiGIF

**Pull request merged**
