### PR TITLE
feat(spoolman): multi-tool support

### PR DESCRIPTION
**Pull request by matmen**
Closes https://github.com/fluidd-core/fluidd/issues/1269

Adds a new tool selection dropdown to the spoolman card when one or more `gcode_macro`s with a `spool_id` variable are detected. Emits a `SET_GCODE_VARIABLE` command to update the tools associated spool.

screenshot

[ Docs](https://github.com/fluidd-core/fluidd/assets/25269274/4b64343a-d8a4-4ad9-a8ba-ac8834f75bbe)

When a tool has a spool ID set, the tools "color dot" will be replaced by a filament spool icon in the corresponding filaments color (like in the spool selection modal).
Persisting settings available using Klipper's `[save_variables]` module.

### CODE REVIEW

**Comment by pedrolamas** [comment]
> When a tool has a spool ID set, the tools "color dot" will be replaced by a filament spool icon in the corresponding filaments color (like in the spool selection modal).

The only issue I see with this is if the spool color is gray, it won't show up if Fluidd is using Dark theme (same for white spool in Light theme), hence why I was using that "dot" thing!

**Comment by matmen** [comment]
The same issue exists in the spool selection dialog, I think this should be an easy fix by just adding an outline to the spool icon

**Comment by pedrolamas** [comment]
> ...adding an outline to the spool icon

not sure if that is possible, but if you manage to do it, I am **very** interested! 😁

**Comment by matmen** [comment]
I think this should work:

image
image
image
image

**Comment by pedrolamas** [comment]
> I think this should work:

Sure, I personally can see it fine, though I am not sure that we can claim that it is "accessible" to every seeing user!

Also, a 16-bit screen or lower might be problematic... but granted, nowadays these are extremely rare! 😁

**Comment by matmen** [comment]
Yeah, that was my thought too, but I couldn't really figure out how to make it accessible _and_ have it look decent. Even the current solution is kinda meh (especially on smaller screens), I think ideally we'd want a light or dark background color on the spool icon depending on the lightness of the filament color - or maybe even a multi-tone icon?

**Comment by fweber3** [comment]
> Yeah, that was my thought too, but I couldn't really figure out how to make it accessible _and_ have it look decent. Even the current solution is kinda meh (especially on smaller screens), I think ideally we'd want a light or dark background color on the spool icon depending on the lightness of the filament color - or maybe even a multi-tone icon?

I'm not a big designer, but here's two triggers outside of your box:
How about using a contrasting color for accessibility BUT make it dashed/dotted (lines) or striped/polkadots (areas)? How about a strikethrough? ("big red cross", or something less in-your-face).

**Comment by pedrolamas** [comment]
I am not sure what is the best course of action here in terms of layout (I too am not a designer), but I am happy to review this in terms of functionality and we can revisit this topic in a later change!

**Comment by pedrolamas** [comment]
I admit I am troubled with the whole `SET_GCODE_VARIABLE`...

I honestly don't think we should be doing this from Fluidd side because if the user has a KlipperScreen or also uses Mainsail, it will not work until they too make the same changes...

In my view, this should either be done on Moonraker side, or somehow directly from Klipper side.

**Comment by matmen** [comment]
> Any particular reason for that `macro.name.toUpperCase()`?

That's just so the macro name is displayed in upper case in the modals, in theory we can do this with CSS instead.
Either way should be fine I think, as currently only the "change spool" dropdown and spool selection modal consume the `targetableMacros` result.

> I admit I am troubled with the whole `SET_GCODE_VARIABLE`...
> 
> I honestly don't think we should be doing this from Fluidd side because if the user has a KlipperScreen or also uses Mainsail, it will not work until they too make the same changes...
> 
> In my view, this should either be done on Moonraker side, or somehow directly from Klipper side.

Well, having an API to set gcode macro variables directly would be optimal, but AFAIK there isn't one right now. I think the `spool_id` variable name should be fine across frontends, and if the functionality to set gcode macro variables via Moonraker gets added in the future this can still be refactored.

**Review by pedrolamas — APPROVED** [review]
Not fully convinced with the usage of the variables to store state (as that will not be reflected in other frontends), but I think we can go with this and revisit later if it comes to a common solution!

**Pull request merged**
