### PR TITLE
feat: Editor close confirmations with unsaved changes

### PR DESCRIPTION
**Pull request by matmen**
Adds a close confirmation modal when closing the editor when its contents are dirty
Fixes https://github.com/cadriel/fluidd/issues/384
Unsaved Changes modal

### CODE REVIEW

**Comment by Biorn1950** [comment]
Ok but with an option to disable it in the settings. I live better without popup ;)

**Comment by matmen** [comment]
Done - added a config option to the General section
Config Option

**Review by eduncan911 — DISMISSED** [review]
LGTM.  However, you need to fix the conflicts before we can merge.

**Review by Biorn1950 — APPROVED** [review]

**Review by eduncan911 — APPROVED** [review]

**Comment by pedrolamas** [comment]
Thanks for this @matmen, I just tried it and it is working marvelously!!

**Pull request merged**
