### PR TITLE
feat: temperature rate of change

### LINKED ISSUE #409: Add Rate of Change column to Thermals
Please considering add a Rate of Change column to the Thermals table.

It would be nice to see rate of change for heating or cooling extruders, heated beds, etc. to establish some notion of impact of cooling fans or if risk exists for warping a bed.

### PR DESCRIPTION
**Pull request by matmen**
This PR adds a Rate of Change column for heater temperatures to the Thermals card, toggleable via a new settings context menu (disabled by default).
The calculated rate of change is based on a rolling average of the last 5 data points to filter out sensor reading fluctuations. Absolute deltas of `< 0.05` are filtered out to prevent a constant flipping of the RoC sign when the RoC is `~0`.
Discussion is welcome. Closes #409.

image
image

### CODE REVIEW

**Comment by StuSerious** [comment]
Love this! 
Super useful in multi extrusion printing to get the switch times just perfect, and overall a cool metric to monitor and brag about!

**Comment by Biorn1950** [comment]
@matmen what do you think to have all the settings icons aligned next to the arrow like that:
Capture d’écran 2022-01-30 à 02 35 39

everything else is ok.

**Comment by matmen** [comment]
I must have overlooked that. Fixed.
image

**Review by Biorn1950 — DISMISSED** [review]
LGTM

**Review by pedrolamas — APPROVED** [review]

**Comment by matmen** [comment]
Screenshot on [Thermals Chart](https://docs.fluidd.xyz/features/chart) needs to be updated, and settings dropdown may need to be documented?

**Comment by NyxCode** [comment]
Love this feature - however, I'd like to see this for all thermistors. Especially for a chamber thermistor this would be awesome.

**Comment by pedrolamas** [comment]
> Love this feature - however, I'd like to see this for all thermistors. Especially for a chamber thermistor this would be awesome.

@NyxCode that has just been added, it's available right now on the `develop` branch and will be part of the next release! 🙂

**Pull request merged**
