### PR TITLE
feat: adds Upload and Print button to AppBar

### LINKED ISSUE #804: Upload & Start button
### Is your feature request related to a problem? Please describe

Uploading and printing .gcode files takes too long.

### Describe the solution you'd like

Add a button like on Duet Web Control to start prints faster.
I think it will the best in a similar style to the notification bell

Like this: (A)

Bildschirmfoto 2022-07-30 um 00 51 02

or: (B)

Bildschirmfoto 2022-07-30 um 00 47 51

### Describe alternatives you've considered

_No response_

### Additional information

Bildschirmfoto 2022-07-30 um 00 33 36

### PR DESCRIPTION
**Pull request by pedrolamas**
Adds a new optional Upload and Print button to the top navigation bar.

image

image

image

Button is hidden while printing something.

This button visibility is configurable in the settings, and defaults to visible:

image

Closes #804 

Signed-off-by: Pedro Lamas <pedrolamas@gmail.com>

### CODE REVIEW

**Comment by matmen** [comment]
I haven't had a chance to take a look at this yet, but I'm wondering if the button should be disabled instead of hidden when printing? Otherwise the e-stop button would shift..

**Comment by pedrolamas** [comment]
Makes sense, I'll quickly change it! 🙂

**Comment by pedrolamas** [comment]
Done, it will now disable the button if `printing` or `paused` instead of hiding it!

**Review by matmen — APPROVED** [review]
LGTM

**Pull request merged**
